version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - echo "Current directory:"
      - pwd
      - ls -la
      - echo "Installing dependencies"
      - npm install

  build:
    commands:
      - echo "Build started"
      - npm run build --if-present

artifacts:
  files:
    - '**/*'
